export const KIT_PRODUCTS = [
  'Hoover',
  'Henry bags',
  'PacVac Bags',
  'EC2',
  'EC4',
  'EC6',
  'EC7',
  'EC9',
  'Blue roll',
  'Blue bucket',
  'Blue mop handle',
  'Blue mop head',
  'Red bucket',
  'Red mop handle',
  'Red mop head',
  'Tshirt',
  'Cloths',
  'Dust pan & brush',
  'Face masks',
  'High vis',
  'Gloves',
  'Floor cleaner',
];
